import 'package:path_provider/path_provider.dart';

// `objectbox.g.dart` is generated by build_runner at the lib/ root. It contains
// the top-level `openStore` function, the `Store` type re-export, and the schema
// for every @Entity class.
// Run: flutter pub run build_runner build --delete-conflicting-outputs
import '../objectbox.g.dart';

/// Owns the app's single ObjectBox [Store]. Created once at startup by the
/// injectable module and injected downstream via `get_it`.
class ObjectBoxDatabase {
  final Store store;

  ObjectBoxDatabase._(this.store);

  static Future<ObjectBoxDatabase> create() async {
    final docsDir = await getApplicationDocumentsDirectory();
    final store = await openStore(
      directory: '${docsDir.path}/objectbox',
    );
    return ObjectBoxDatabase._(store);
  }
}
